common_params:
  respawn_request: https://w1.dwar.ru/action_run.php?code=RESURRECT&url_success=area.php&url_error=area.php&in[mode_id]=1
  server_url: https://w1.dwar.ru

users:
  dijkstra:
    resources_to_collect:
      - "1"
      - "2"
      # ... other resources
    instance:
    signature:  # User specific
    resource_request_template:
    cookie:
    # Use common respawn_request
    profile_dir:
    nickname:
    username:
    password:
    srv: